name = "matchpay-cf"
compatibility_date = "2025-01-15"

[[d1_databases]]
binding = "DB"
database_name = "matchpay"
database_id = "REEMPLAZA_EN_CLOUDFLARE"

[[kv_namespaces]]
binding = "KV"
id = "REEMPLAZA_EN_CLOUDFLARE"
